Able conn to mySQL server but fail to conn to db
TLDR: Use `%s` inside the query for `CREATE DATABASE`. Todo: verify if connection to database isn't working because of docker or because of python. We believe its the ladder because our output shows "Successfully connected to database"

Current error:
```python
Server connection successful!
Database created successfully!
Error connecting to the database: 1049 (42000): Unknown database 'discodb-mini-top-100'
Traceback (most recent call last):
  File "C:\Users\jturn\Documents\GitHub\project-discodb\db\Miniature database code\setup_sql.py", line 284, in <module>
    create_artist_tables(connection)
  File "C:\Users\jturn\Documents\GitHub\project-discodb\db\Miniature database code\setup_sql.py", line 92, in create_artist_tables
    execute_and_commit(connection, query)
  File "C:\Users\jturn\Documents\GitHub\project-discodb\db\Miniature database code\setup_sql.py", line 247, in execute_and_commit
    cursor = connection.cursor()
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'
```

Originally, Got error because mysql python was trying to put quotes around the string, so it was ''discodb-mini-...'' rather than just 'discodb-mini...'
```ps
PS C:\...\Miniature database code>python .\setup_sql.py
Server connection successful!
Error creating database: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''discodb-mini-top-100'' at line 1
```