[setup_sql] Fix paths. Attempt run w/ docker mysql
The file I'm trying to run is `setup_sql.py`
- I was able to run it, kind of!
- **I think it's just unable to connect to the mySQL docker**
- (maybe) try again with local db url? i.e. `127.0.0.1`

Error:
```
Error connecting to the SQL server: 2003: Can't connect to MySQL server on '127.0.0.1:3306' (10061 No connection could be made because the target machine actively refused it)
Traceback (most recent call last):
  File "C:\Users\jturn\Documents\GitHub\project-discodb\db\Miniature database code\setup_sql.py", line 293, in <module>
    cursor = connection.cursor()
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'
```